Update how the car service binds to services.
Due to recent changes in the background service handling, car service
tests (none-foreground) were not able to bind to services, they were
failing with:

java.lang.IllegalStateException: Not allowed to start service Intent
{...}: app is in background

This change updates how the car service binds to services in
InstrumentClusterService and VmsPublisherService.

Test: runtest -x packages/services/Car/tests/carservice_test/src/com/android/car/test/CarInfoManagerTest.java
Bug: 35360913
Change-Id: If813d39bf1b8a7e4fc41aea2198e1591d807c711